//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Holders = new HashSet<Holder>();
        }
    
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public Nullable<decimal> TotalShare { get; set; }
        public string About { get; set; }
    
        public virtual ICollection<Holder> Holders { get; set; }
    }
}
