//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holder
    {
        public Holder()
        {
            this.Holder_Vote = new HashSet<Holder_Vote>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> TotalShare { get; set; }
        public string AuthorizerName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public string CMND { get; set; }
        public string WorkUnit { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Holder_Vote> Holder_Vote { get; set; }
    }
}
